In [12]:
import pandas as pd
import numpy as np
import sys
sys.path.append('D:\E-Commerce_dynamic_system\src')

<>:4: SyntaxWarning: invalid escape sequence '\E'
<>:4: SyntaxWarning: invalid escape sequence '\E'
C:\Users\bharg\AppData\Local\Temp\ipykernel_7368\2883215098.py:4: SyntaxWarning: invalid escape sequence '\E'
  sys.path.append('D:\E-Commerce_dynamic_system\src')

In [ ]:
from feature_engineering import engineer_all_features

In [16]:
#loading cleaned dataframe
df=pd.read_csv(r'D:\E-Commerce_dynamic_system\data\processed\cleaned_products.csv')

In [19]:
engineer_all_features(df)

,Unnamed: 0,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_sponsored,is_couponed,sustainability_badges,collected_at,discounted_amount,discount_pct,value_score,demand_score,estimated_revenue
0,0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,0,1,0,0,2025-08-21 11:14:29,69.32,43.597484,0.051293,0.0030,26904.0
1,1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,0,1,0,1,2025-08-21 11:14:29,6.00,37.523452,0.430430,0.0600,59940.0
2,2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,0,1,0,1,2025-08-21 11:14:29,35.00,10.028653,0.014650,0.0200,628000.0
3,3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,77.00,56.99,1,0,0,1,2025-08-21 11:14:29,-20.01,-35.111423,0.059740,0.1000,770000.0
4,4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,77.00,56.99,0,0,0,1,2025-08-21 11:14:29,-20.01,-35.111423,0.062338,0.1000,770000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41646,42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1.0,100.0,195.99,56.99,0,0,0,1,2025-08-30 19:56:33,-139.00,-243.902439,0.025512,0.0010,19599.0
41647,42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20.0,200.0,89.99,56.99,0,0,0,1,2025-08-30 19:56:33,-33.00,-57.904896,0.046672,0.0020,17998.0
41648,42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57.0,50.0,899.99,56.99,0,0,0,1,2025-08-30 19:56:33,-843.00,-1479.206878,0.004778,0.0005,44999.5
41649,42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102.0,500.0,10.39,15.98,0,0,0,1,2025-08-30 19:56:33,5.59,34.981227,0.452358,0.0050,5195.0
41650,42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75.0,50.0,419.99,499.99,0,0,0,1,2025-08-30 19:56:33,80.00,16.000320,0.010476,0.0005,20999.5

In [20]:
print(df.shape)

(41651, 17)

In [21]:
df.head()

,Unnamed: 0,title,rating,number_of_reviews,bought_in_last_month,current/discounted_price,listed_price,is_best_seller,is_sponsored,is_couponed,sustainability_badges,collected_at,discounted_amount,discount_pct,value_score,demand_score,estimated_revenue
0,0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,0,1,0,0,2025-08-21 11:14:29,69.32,43.597484,0.051293,0.003,26904.0
1,1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,0,1,0,1,2025-08-21 11:14:29,6.00,37.523452,0.430430,0.060,59940.0
2,2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,0,1,0,1,2025-08-21 11:14:29,35.00,10.028653,0.014650,0.020,628000.0
3,3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,77.00,56.99,1,0,0,1,2025-08-21 11:14:29,-20.01,-35.111423,0.059740,0.100,770000.0
4,4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,77.00,56.99,0,0,0,1,2025-08-21 11:14:29,-20.01,-35.111423,0.062338,0.100,770000.0